package main

import (
	"net/http"
	"testing"
) //. "urlutils" //check for my urlutils (my own) package

// Hook up gocheck into the "go test" runner.
func Test(t *testing.T) { TestingT(t) }

type MySuite struct{}

func () TestHelloWorld(c *C) {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://localhost:6060")
	if err != nil {
		// handle err
	}
	c.Assert(err, Equals, nil)
	defer resp.Body.Close()
}
