
	@echo "help: Generates this message"
	@echo "test-coverage: Reports test coverage"

test-coverage:
	@echo "checking test coverage"
	npm test -- --coverage

clean:
	@echo "cleaning cache"
	npm cache clean

	